name: Go

env:
  BINARY_NAME: pm
  GO_VERSION: 1.17

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: $GO_VERSION

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
  
  publish:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: $GO_VERSION

    - name: Build binary
      run: go build -o $BINARY_NAME ./cmd/cli

    - name: Upload binary
      uses: actions/upload-artifact@v2.2.4
      with:
        name: $BINARY_NAME
        path: $BINARY_NAME
        if-no-files-found: error

  smoke-testing:
    runs-on: ubuntu-latest
    needs: [publish]
    steps:
    - name: Download binary
      uses: actions/download-artifact@v2.0.10
      with:
        name: $BINARY_NAME
        path: /bin/$BINARY_NAME
        
    - name: Search for packages
      run: $BINARY_NAME search k9s

    - name: Show info about package
      run: $BINARY_NAME info k9s

    - name: Install packages one-by-one
      run: |
        $BINARY_NAME install k9s
        $BINARY_NAME install kubectx
        $BINARY_NAME install buf
        $BINARY_NAME install legendary
