name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
  
  publish:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build binary
      run: go build -o pm ./cmd/cli

    - name: Upload binary
      uses: actions/upload-artifact@v2.2.4
      with:
        name: pm
        path: pm
        if-no-files-found: error

  smoke-testing:
    runs-on: ubuntu-latest
    needs: [publish]
    steps:
    - name: Download binary
      uses: actions/download-artifact@v2.0.10
      with:
        name: pm
        path: pm
        
    - name: Search for packages
      run: ./pm search k9s

    - name: Show info about package
      run: ./pm info k9s

    - name: Install packages one-by-one
      run: |
        ./pm install k9s
        ./pm install kubectx
        ./pm install buf
        ./pm install legendary
