name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

  smoke-testing:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build and install binary
      run: go install ./cmd/cli
        
    - name: Search for packages
      run: cli search k9s

    - name: Show info about package
      run: cli info k9s

    - name: Install packages one-by-one
      env:
        PM_PACKAGES_PATH: ./packages
      run: |
        cli install k9s
        cli install kubectx
        cli install buf
        cli install legendary
        
    - name: Check if packages were installed and linked correctly
      env:
        PM_PACKAGES_PATH: ./packages
      run: |
        $(PM_PACKAGES_PATH)/buf --version
        $(PM_PACKAGES_PATH)/kubectx --version
        $(PM_PACKAGES_PATH)/k9s version
        $(PM_PACKAGES_PATH)/legendary --version

  publish:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build binary
      run: go build ./cmd/cli

    - name: Upload binary
      uses: actions/upload-artifact@v2.2.4
      with:
        name: cli
        path: cli
        if-no-files-found: error
